FROM debian:bookworm AS base

# Create user and group
RUN groupadd -r ollama && useradd -r -g ollama ollama
RUN mkdir -p /home/ollama && chown -R ollama:ollama /home/ollama


# Get the Ollama binary
FROM base AS get_ollama

RUN apt-get update && apt-get install -y wget
USER ollama

RUN mkdir -p /home/ollama/ollama && chown -R ollama:ollama /home/ollama/ollama
WORKDIR /home/ollama/ollama

RUN wget https://github.com/ollama/ollama/releases/download/v0.1.36/ollama-linux-amd64 -O ollama && \
    chmod +x ollama


# Setup Ollama environment
FROM base AS ollama_env

# Install ca-certificates for pulling models
RUN apt-get update && apt-get install -y ca-certificates

ENV OLLAMA_HOST=0.0.0.0
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all

USER ollama

# Copy the Ollama binary from the previous stage
COPY --from=get_ollama /home/ollama/ollama/ollama /usr/local/bin/ollama
# Make directory so named volumes dont create via root
RUN mkdir -p /home/ollama/.ollama/models

WORKDIR /home/ollama/


FROM ollama_env AS ollama_embedding

# Copy the startup script
COPY --chown=ollama:ollama ./scripts/ollama_embedding_startup.sh /home/ollama/scripts/ollama_embedding_startup.sh
RUN chmod +x /home/ollama/scripts/ollama_embedding_startup.sh

EXPOSE 11434
ENTRYPOINT [ "./scripts/ollama_embedding_startup.sh" ] 


FROM ollama_env AS ollama_chat

# Copy the startup script
COPY --chown=ollama:ollama ./scripts/ollama_chat_startup.sh /home/ollama/scripts/ollama_chat_startup.sh
RUN chmod +x /home/ollama/scripts/ollama_chat_startup.sh

EXPOSE 11434
ENTRYPOINT [ "./scripts/ollama_chat_startup.sh" ]
